FROM node:18
LABEL authors="Ole"

WORKDIR /usr/app
RUN apt update && curl -sLO https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-amd64.deb && dpkg -i fastfetch-linux-amd64.deb
COPY package*.json ./
RUN npm install
COPY prisma .
ARG DATABASE_URL
ENV DATABASE_URL $DATABASE_URL
RUN npx prisma db pull && npx prisma generate
COPY . ./
RUN npm run build
CMD ["npm", "run", "dev"]
