export type RegexpType = { match: RegExpMatchArray };
export type RespType = { anime: string, character: string, quote: string };
export type Categories = "Administration"
    | "Anime"
    | "Emotes"
    | "Fun"
    | "Gambling"
    | "Moderation"
    | "NSFW"
    | "Owner only"
    | "Roles"
    | "Server settings"
    | "Utility"
    | "Images"
    | "Interactions"
